### ISSUE TITLE
Theme: retrieve highlight.js from npm

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonita-documentation-theme#126]
highlight.js assets are currently stored in the repository. It is also declared in the [package.json](https://github.com/bonitasoft/bonita-documentation-theme/blob/60fe1f269d65b5fff5f76a1800af62b1dc2f8ebb/package.json) file but not used.
So, try to retrieve the assets from npm like we do for docsearch

**Comment by jeromecambon** [comment]
I spent time on this one. 
I have an issue because highlight.min.js is not delivered in the npm package... So it cannot be concatanated in libs.js nor referenced in a <script> tag. So the npm pkg seems difficult to use here.
I agree it is not ideal because we will not be helped by dependabot to bump the version.
But not sure it deserve to spend more time.
So I suggest to close this issue.

**Comment by tbouffard** [comment]
@jeromecambon the decision about this issue was taken here: https://github.com/bonitasoft/bonita-documentation-theme/issues/126#issuecomment-1260819647

**Comment by jeromecambon** [comment]
I also tried [Prism](https://prismjs.com), which is an alternative. Unfortunately it does not work better for us, since it requires to load additional languages support separately.
